# Generated by Django 5.1.4 on 2025-03-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_head_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=50)),
                ('employee_underwork', models.IntegerField()),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('room_no', models.CharField(max_length=20, unique=True)),
                ('no_of_beds', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=11)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='MultiCuisineRestaurantService',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_type', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('service_date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.service')),
            ],
            options={
                'db_table': 'multi_cuisine_restaurant_services',
            },
        ),
        migrations.CreateModel(
            name='LuxurySpaService',
            fields=[
                ('spa_id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_type', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('service_date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.service')),
            ],
            options={
                'db_table': 'luxury_spa_services',
            },
        ),
        migrations.CreateModel(
            name='HousekeepingService',
            fields=[
                ('housekeeping_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Working', 'Working'), ('Remaining', 'Remaining')], max_length=25)),
                ('service_date', models.DateField()),
                ('staff_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.service')),
            ],
            options={
                'db_table': 'housekeeping_services',
            },
        ),
        migrations.CreateModel(
            name='FreeWifiService',
            fields=[
                ('wifi_id', models.AutoField(primary_key=True, serialize=False)),
                ('wifi_name', models.CharField(max_length=50)),
                ('wifi_password', models.CharField(max_length=50)),
                ('service_date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.service')),
            ],
            options={
                'db_table': 'free_wifi_services',
            },
        ),
        migrations.CreateModel(
            name='FitnessCenterService',
            fields=[
                ('fitness_center_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_count', models.IntegerField()),
                ('service_date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.service')),
            ],
            options={
                'db_table': 'fitness_center_services',
            },
        ),
        migrations.CreateModel(
            name='TheaterService',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('service_date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.service')),
            ],
            options={
                'db_table': 'theater_services',
            },
        ),
    ]
