# Generated by Django 5.1.4 on 2025-03-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('attendance_status', models.CharField(choices=[('P', 'Full Day Present'), ('H', 'Half Day Present'), ('A', 'Full Day Absence')], max_length=1)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_date', models.DateField(null=True)),
                ('email_id', models.CharField(max_length=100, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Medical Leave', 'Medical Leave'), ('Other', 'Other')], max_length=25)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
    ]
