# Generated by Django 5.1.4 on 2025-03-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.booking'),
        ),
        migrations.AddField(
            model_name='guest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.booking'),
        ),
    ]
