# Generated by Django 5.1.4 on 2025-03-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_datetime', models.DateTimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.guest')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', to_field='room_no')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
